### ISSUE TITLE
Usage question. How to change the target email address the contact me form sends to

### ISSUE THREAD

**Issue by dmaahs2017** [dave-tucker/zola-clean-blog#3]
How do I change the email address that the contact me form will send to?

I'm deploying to a raspberry Pi, using nginx to serve the static site.

**Comment by thelema** [comment]
Looking at the generated html, it looks like this is just a template for a contact form, and there's no logic for directing the information in that form to any destination.

**Comment by dave-tucker** [comment]
That's correct. Form handling on my site uses Netlify's Forms handling.

**Comment by dmaahs2017** [comment]
Thanks, I figured it out using formspree.
